# Generated by Django 3.1.3 on 2021-01-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='/images/avatar.jpg', null=True, upload_to='staff/pictures', verbose_name='profile picture'),
        ),
    ]
