# Generated by Django 3.1.3 on 2021-01-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20201222_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default=None, upload_to='staff/pictures', verbose_name='profile picture'),
        ),
    ]
