# Generated by Django 3.1.3 on 2020-12-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixservice',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='sellservice',
            name='final_price',
        ),
    ]
