# Generated by Django 3.1.3 on 2020-11-23 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0002_auto_20201122_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which object was modified', verbose_name='modified at ')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which object was modified', verbose_name='modified at ')),
                ('name', models.CharField(max_length=15)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.brand')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which object was modified', verbose_name='modified at ')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which object was modified', verbose_name='modified at ')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('sn', models.CharField(blank=True, max_length=30)),
                ('price', models.FloatField()),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('used', 'De uso')], max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('available', 'Disponible'), ('out_of_stock', 'Agotado')], default='disponible', max_length=30)),
                ('modelo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stock.devicemodelo')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='devicemodelo',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.devicetype'),
        ),
    ]
