# Generated by Django 3.1.3 on 2020-11-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20201125_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='type_of_sparepart',
        ),
    ]
