# Generated by Django 3.1.3 on 2020-11-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_devicemodel_type_of_sparepart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparttype',
            name='main_property_value',
            field=models.CharField(max_length=20),
        ),
    ]
