# Generated by Django 3.1.3 on 2020-12-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_profile_is_password_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
