# Generated by Django 3.1.3 on 2020-11-23 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceModelo',
            new_name='DeviceModel',
        ),
    ]
