# Generated by Django 3.1.3 on 2020-11-25 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20201123_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparepart',
            old_name='sparepart_device',
            new_name='device_model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modelo',
        ),
        migrations.AddField(
            model_name='product',
            name='device_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.devicemodel'),
        ),
    ]
