# Generated by Django 3.1.3 on 2020-11-30 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20201130_0034'),
        ('customers', '0003_auto_20201129_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdevice',
            name='device_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.devicemodel'),
        ),
    ]
