# Generated by Django 3.1.3 on 2020-12-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20201201_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cellphone_number',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
    ]
