# Generated by Django 3.1.3 on 2021-01-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='client',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='time',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cellphone_number',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
