# Generated by Django 3.1.3 on 2021-01-25 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210124_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
