# Generated by Django 3.1.3 on 2021-01-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_contact_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='time',
        ),
    ]
