# Generated by Django 3.1.3 on 2020-11-22 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which object was modified', verbose_name='modified at ')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be enteredin format: +5399999999. Upto 15 digits allowed.', regex='\\+?2?\\d{8-15}$')])),
                ('cellphone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be enteredin format: +5399999999. Upto 15 digits allowed.', regex='\\+?2?\\d{8-15}$')])),
                ('address', models.CharField(max_length=30)),
                ('ci', models.PositiveIntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='Ci must have 11 numbers', regex='{11}\\d$')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
