# Generated by Django 3.1.3 on 2021-01-23 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cellphone_number',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ci',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Ci must have 11 numbers', regex='\\d{1,11}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
