# Generated by Django 3.1.3 on 2021-01-16 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellservice',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixservice',
            name='clients_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customerdevice'),
        ),
        migrations.AddField(
            model_name='fixservice',
            name='resources',
            field=models.ManyToManyField(to='stock.SparePart'),
        ),
        migrations.AddField(
            model_name='fixservice',
            name='service_type',
            field=models.ManyToManyField(to='services.ServiceType'),
        ),
        migrations.AddField(
            model_name='fixservice',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyservice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
        migrations.AddField(
            model_name='buyservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.sellservice'),
        ),
    ]
