# Generated by Django 3.1.3 on 2021-01-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210116_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixservice',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixservice',
            name='warrantyoff',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellservice',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellservice',
            name='warrantyoff',
            field=models.DateField(blank=True, null=True),
        ),
    ]
