# Generated by Django 3.1.3 on 2021-01-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('services', '0003_auto_20210116_0208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyService',
            new_name='ServiceProduct',
        ),
    ]
