# Generated by Django 3.1.3 on 2020-11-25 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customerdevice'),
        ('stock', '0003_auto_20201125_0107'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which object was modified', verbose_name='modified at ')),
                ('service_name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which object was modified', verbose_name='modified at ')),
                ('price', models.FloatField()),
                ('discount', models.FloatField(blank=True)),
                ('final_price', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=100)),
                ('has_warranty', models.BooleanField(default=False)),
                ('warrantyoff', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('products', models.ManyToManyField(to='stock.Product')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FixService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which object was modified', verbose_name='modified at ')),
                ('price', models.FloatField()),
                ('discount', models.FloatField(blank=True)),
                ('final_price', models.FloatField()),
                ('has_warranty', models.BooleanField(default=False)),
                ('warrantyoff', models.DateField()),
                ('description', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'pendiente'), ('finished', 'Terminado')], default='pending', max_length=20)),
                ('clients_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customerdevice')),
                ('resources', models.ManyToManyField(to='stock.SparePart')),
                ('service_type', models.ManyToManyField(to='services.ServiceType')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
