# Generated by Django 3.1.3 on 2020-12-01 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20201122_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cellphone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be enteredin format: +5399999999. Upto 15 digits allowed.', regex='\\+?1?\\d{8-15}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be enteredin format: +5399999999. Upto 15 digits allowed.', regex='\\+?1?\\d{8-15}$')]),
        ),
    ]
