# Generated by Django 3.1.3 on 2020-11-22 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='ci',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='Ci must have 11 numbers', regex='\\d{1,11}$')]),
        ),
    ]
