# Generated by Django 3.1.3 on 2020-12-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20201201_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
